
services:

  db:
    image: linuxserver/mariadb
    #image: mariadb:10.5
    #image: mysql:8.0
    #image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wd3_db
    ports:
      - 3306:3306  #mssql 1433:1433
    #environment:  #mssql - https://hub.docker.com/_/microsoft-mssql-server
      #ACCEPT_EULA: "Y"
      #MSSQL_SA_PASSWORD: example_123
      ##MSSQL_PID: ....  #nemusi byt zadane, default: Developer, ... Express, Standard, Enterprise, EnterpriseCore 
    environment:  #mysql,mariadb
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - MYSQL_ROOT_PASSWORD=wd333
      - MYSQL_DATABASE=wd333
      - MYSQL_USER=wd333
      - MYSQL_PASSWORD=wd333
    volumes:
      #- ./app/db:/var/lib/mysql                                     #PC
      #- /home/pi/Documents/Backups/uniot/db/data:/var/lib/mysql    #Raspberry Pi
      - ./app/db/config:/config                                    #PC + linuxserver/mariadb
      #- /home/pi/Documents/Backups/uniot/db/config:/config         #Raspberry Pi + linuxserver/mariadb
    networks:
      - wd3_net
    restart: unless-stopped
    
  web:
    #image: japisoft/wd3
    build: WD3
    container_name: wd3_web
    ports:
      - 8080:80
    environment:
      DBServer: db
      DBPort: 3306  #mssql 1433, mysql 3306
      DBUser: wd333
      DBPassword: wd333
      Database: wd333
      ASPNETCORE_ENVIRONMENT: Development  
      #ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./app/wwwroot:/app/wwwroot
    depends_on:
      - db
    networks:
      - wd3_net
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wd3_phpmyadmin
    ports:
      - 4040:80
    environment:
      - PMA_HOST=db
      #- PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=wd333
    depends_on:
      - db
    networks:
      - wd3_net
    restart: unless-stopped


#volumes:
#    wd3_database_data:
#     name: wd3_database_data

networks:
  wd3_net:
    name: wd3_net
